### ISSUE TITLE
[P2] calamari-7seg-segments.fbp and calamari-buttons-rgb-led.fbp failed to run on minnowboard

### ISSUE THREAD

**Issue by dborquez** [solettaproject/soletta#1006]
**Soletta version:** V5
**sha1:** ed93a6f8d1d572f1e67da78651be268758f93631

**Output details:**
https://gist.github.com/dborquez/ce1a3fa5d4f2b77c346f

Thank you.

**Comment by bdilly** [comment]
@brunobottazzini could you please close it if was fixed already? I remember you mentioned calamari demos are working with V6.

**Comment by brunobottazzini** [comment]
@bdilly we had tested it and we got problems only in the samples:

 - calamari-7seg-segments
 - calamari-button-accumulator-persistence
 - calamari-buttons-rgb-led

These problems should be fixed with the PR: https://github.com/solettaproject/soletta/pull/1462.

For the next release everything should be normal.

**Comment by bdilly** [comment]
cool.
so I'm closing this issue
