### ISSUE TITLE
GET request against iotivity's ocserverbasicops fails

### ISSUE THREAD

**Issue by gabrielschulhof** [solettaproject/soletta#1389]
iotivity seems not to be able to parse the payload.

https://gist.github.com/gabrielschulhof/b4f8a423983e83d9d7ae

**Comment by gabrielschulhof** [comment]
I built iotivity with default flags.

**Comment by otaviobp** [comment]
Payload was created incorrectly when using a callback to fill the payload, but no data was added. You can use NULL instead of using no_payload callback.
Fix to this issue was pushed in pr #1399 and get.c is suppose to work against iotivity servers.
Please reopen ticket if problem was not solved for you.
