### ISSUE TITLE
use of python3

### ISSUE THREAD

**Issue by bapclenet** [solettaproject/soletta#1469]
```
The following (required) dependencies were not met:

python module: jsonschema

If you've just installed it, run: make reconf
For more information/options, run: make help
```

You should add that you use python 3 here beacause I tried to install jsonschema with pip (which was linked to python 2.7) and Soletta couldn't find it after the install because it has not been added to python3

**Comment by ibriano** [comment]
Ah, those are listed as dependencies somewhere in Soletta's documentation.

On Feb 24, 2016, at 07:13, bapclenet <notifications@github.com<mailto:notifications@github.com>> wrote:


The following (required) dependencies were not met:

python module: jsonschema

If you've just installed it, run: make reconf
For more information/options, run: make help


You should add that you use python 3 here beacause I tried to install jsonschema with pip (which was linked to python 2.7) and Soletta couldn't find it after the install because it has not been added to python3

�

**Comment by dorileo** [comment]
Since dependency-resolver.py is a python3 script this will consider all the python tests/checks to be python3, the message can be changed to reflect it. I'm cooking a simple patch for that.

**Comment by dorileo** [comment]
pull request #1470 fixes the issue.

**Comment by bapclenet** [comment]
Ok thanks
